# Generated by Django 5.0 on 2023-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_product', to='product.product', verbose_name='basket'),
        ),
    ]
